apiVersion: apps.kruise.io/v1alpha1
kind: SidecarSet
metadata:
  name: test-sidecarset
spec:
  updateStrategy:
    type: RollingUpdate
    partition: 5
  selector: 
    matchLabels:
      app: nginx
  containers:
  - name: sidecar1
    image: busybox:1.35.0
    command: [ "/bin/sh", "-c", "sleep 5 && touch /tmp/aa.txt && sleep 999d" ]  #通过注入提前完成初始化
    volumeMounts:
    - name: log-volume
      mountPath: /var/log
  volumes:
  - name: log-volume
    emptyDir: {}