apiVersion: apps.kruise.io/v1alpha1
kind: DaemonSet
metadata:
  name: nginx
  namespace: default
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      #rollingUpdateType: InPlaceIfPossible #使用原地升级
      partition: 2   #进行恢度发布，保留旧版本一个
      #paused: true  #如果设置true就暂停服务 
  selector:
    matchLabels:
      k8s-app: nginx
  template:
    metadata:
      labels:
        k8s-app: nginx
    spec:
      containers:
      - image: nginx:1.7.9 #修改点2：修改nginx镜像,只修改镜像的版本会当成原地升级的场景
        name: nginx
        ports:
        - name: http
          containerPort: 80